-- Generated GUI code (place in a LocalScript or ModuleScript)
local huehue = Instance.new("ScreenGui")
huehue.Parent = nil --[[ e.g. PlayerGui ]]
huehue.Enabled = true
huehue.SafeAreaCompatibility = Enum.SafeAreaCompatibility.FullscreenExtension
huehue.ResetOnSpawn = false
huehue.IgnoreGuiInset = false
huehue.Name = "huehue"
huehue.DisplayOrder = 0
huehue.ZIndexBehavior = Enum.ZIndexBehavior.Global
huehue.ScreenInsets = Enum.ScreenInsets.CoreUISafeInsets
huehue.ClipToDeviceSafeArea = true
  local Frame = Instance.new("ImageLabel")
  Frame.Parent = huehue
  Frame.LayoutOrder = 0
  Frame.Active = false
  Frame.Interactable = true
  Frame.SizeConstraint = Enum.SizeConstraint.RelativeXY
  Frame.ZIndex = 1
  Frame.BorderSizePixel = 0
  Frame.SliceCenter = Rect.new(100, 100, 100, 100)
  Frame.Draggable = false
  Frame.ScaleType = Enum.ScaleType.Slice
  Frame.Transparency = 1
  Frame.SelectionOrder = 0
  Frame.BackgroundColor3 = Color3.fromRGB(45, 0, 34)
  Frame.ImageTransparency = 0
  Frame.Selectable = false
  Frame.AnchorPoint = Vector2.new(0, 0)
  Frame.Image = "rbxassetid://3570695787"
  Frame.TileSize = UDim2.new(1, 0, 1, 0)
  Frame.BorderColor = BrickColor.new("Black")
  Frame.ImageContent = Content.fromUri("rbxassetid://3570695787")
  Frame.AutomaticSize = Enum.AutomaticSize.None
  Frame.Size = UDim2.new(0, 579, 0, 290)
  Frame.ClipsDescendants = false
  Frame.BorderColor3 = Color3.fromRGB(27, 42, 53)
  Frame.Visible = false
  Frame.ImageColor3 = Color3.fromRGB(34, 34, 34)
  Frame.BorderMode = Enum.BorderMode.Outline
  Frame.Rotation = 0
  Frame.ImageRectOffset = Vector2.new(0, 0)
  Frame.BackgroundTransparency = 1
  Frame.Position = UDim2.new(0.10418597608804703, 0, 0.16364876925945282, 0)
  Frame.SliceScale = 0.11999999731779099
  Frame.ImageRectSize = Vector2.new(0, 0)
  Frame.ResampleMode = Enum.ResamplerMode.Default
  Frame.Name = "Frame"
    local ImageLabel_6263 = Instance.new("ImageLabel")
    ImageLabel_6263.Parent = Frame
    ImageLabel_6263.LayoutOrder = 0
    ImageLabel_6263.Active = false
    ImageLabel_6263.Interactable = true
    ImageLabel_6263.SizeConstraint = Enum.SizeConstraint.RelativeXY
    ImageLabel_6263.ZIndex = 1
    ImageLabel_6263.BorderSizePixel = 1
    ImageLabel_6263.SliceCenter = Rect.new(100, 100, 100, 100)
    ImageLabel_6263.Draggable = false
    ImageLabel_6263.ScaleType = Enum.ScaleType.Slice
    ImageLabel_6263.Transparency = 1
    ImageLabel_6263.SelectionOrder = 0
    ImageLabel_6263.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
    ImageLabel_6263.ImageTransparency = 0
    ImageLabel_6263.Selectable = false
    ImageLabel_6263.AnchorPoint = Vector2.new(0, 0)
    ImageLabel_6263.Image = "rbxassetid://3570695787"
    ImageLabel_6263.TileSize = UDim2.new(1, 0, 1, 0)
    ImageLabel_6263.BorderColor = BrickColor.new("Black")
    ImageLabel_6263.ImageContent = Content.fromUri("rbxassetid://3570695787")
    ImageLabel_6263.AutomaticSize = Enum.AutomaticSize.None
    ImageLabel_6263.Size = UDim2.new(0, 146, 0, 69)
    ImageLabel_6263.ClipsDescendants = false
    ImageLabel_6263.BorderColor3 = Color3.fromRGB(27, 42, 53)
    ImageLabel_6263.Visible = true
    ImageLabel_6263.ImageColor3 = Color3.fromRGB(76, 76, 76)
    ImageLabel_6263.BorderMode = Enum.BorderMode.Outline
    ImageLabel_6263.Rotation = 0
    ImageLabel_6263.ImageRectOffset = Vector2.new(0, 0)
    ImageLabel_6263.BackgroundTransparency = 1
    ImageLabel_6263.Position = UDim2.new(0.741837203502655, 0, 0.755788266658783, 0)
    ImageLabel_6263.SliceScale = 0.11999999731779099
    ImageLabel_6263.ImageRectSize = Vector2.new(0, 0)
    ImageLabel_6263.ResampleMode = Enum.ResamplerMode.Default
    ImageLabel_6263.Name = "Excute Frame"
    local ImageLabel_9266 = Instance.new("ImageLabel")
    ImageLabel_9266.Parent = Frame
    ImageLabel_9266.LayoutOrder = 0
    ImageLabel_9266.Active = false
    ImageLabel_9266.Interactable = true
    ImageLabel_9266.SizeConstraint = Enum.SizeConstraint.RelativeXY
    ImageLabel_9266.ZIndex = 1
    ImageLabel_9266.BorderSizePixel = 1
    ImageLabel_9266.SliceCenter = Rect.new(100, 100, 100, 100)
    ImageLabel_9266.Draggable = false
    ImageLabel_9266.ScaleType = Enum.ScaleType.Slice
    ImageLabel_9266.Transparency = 1
    ImageLabel_9266.SelectionOrder = 0
    ImageLabel_9266.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    ImageLabel_9266.ImageTransparency = 0
    ImageLabel_9266.Selectable = false
    ImageLabel_9266.AnchorPoint = Vector2.new(0, 0)
    ImageLabel_9266.Image = "rbxassetid://3570695787"
    ImageLabel_9266.TileSize = UDim2.new(1, 0, 1, 0)
    ImageLabel_9266.BorderColor = BrickColor.new("Black")
    ImageLabel_9266.ImageContent = Content.fromUri("rbxassetid://3570695787")
    ImageLabel_9266.AutomaticSize = Enum.AutomaticSize.None
    ImageLabel_9266.Size = UDim2.new(0, 576, 0, 176)
    ImageLabel_9266.ClipsDescendants = false
    ImageLabel_9266.BorderColor3 = Color3.fromRGB(27, 42, 53)
    ImageLabel_9266.Visible = true
    ImageLabel_9266.ImageColor3 = Color3.fromRGB(74, 74, 74)
    ImageLabel_9266.BorderMode = Enum.BorderMode.Outline
    ImageLabel_9266.Rotation = 0
    ImageLabel_9266.ImageRectOffset = Vector2.new(0, 0)
    ImageLabel_9266.BackgroundTransparency = 1
    ImageLabel_9266.Position = UDim2.new(0, 0, 0.14889168739318848, 0)
    ImageLabel_9266.SliceScale = 0.11999999731779099
    ImageLabel_9266.ImageRectSize = Vector2.new(0, 0)
    ImageLabel_9266.ResampleMode = Enum.ResamplerMode.Default
    ImageLabel_9266.Name = "Code Frame"
    local TextBox = Instance.new("TextBox")
    TextBox.Parent = Frame
    TextBox.MultiLine = false
    TextBox.CursorPosition = 1
    TextBox.LineHeight = 1
    TextBox.Active = true
    TextBox.Interactable = true
    TextBox.TextStrokeTransparency = 1
    TextBox.SelectionStart = -1
    TextBox.PlaceholderColor3 = Color3.fromRGB(102, 102, 102)
    TextBox.SizeConstraint = Enum.SizeConstraint.RelativeXY
    TextBox.ZIndex = 1
    TextBox.BorderSizePixel = 1
    TextBox.TextEditable = true
    TextBox.Draggable = false
    TextBox.RichText = true
    TextBox.SelectionOrder = 0
    TextBox.TextYAlignment = Enum.TextYAlignment.Center
    TextBox.TextScaled = true
    TextBox.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    TextBox.Visible = true
    TextBox.FontFace = Font.new("rbxasset://fonts/families/PatrickHand.json", Enum.FontWeight.SemiBold, Enum.FontStyle.Normal)
    TextBox.TextXAlignment = Enum.TextXAlignment.Center
    TextBox.BorderMode = Enum.BorderMode.Outline
    TextBox.Selectable = true
    TextBox.TextWrapped = true
    TextBox.OpenTypeFeatures = ""
    TextBox.TextWrap = true
    TextBox.AnchorPoint = Vector2.new(0, 0)
    TextBox.TextTruncate = Enum.TextTruncate.None
    TextBox.TextTransparency = 0
    TextBox.BorderColor = BrickColor.new("Black")
    TextBox.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
    TextBox.PlaceholderText = "Script Here"
    TextBox.AutomaticSize = Enum.AutomaticSize.None
    TextBox.ShowNativeInput = true
    TextBox.TextSize = 100
    TextBox.TextDirection = Enum.TextDirection.Auto
    TextBox.TextColor3 = Color3.fromRGB(188, 188, 188)
    TextBox.ClipsDescendants = false
    TextBox.BorderColor3 = Color3.fromRGB(27, 42, 53)
    TextBox.Text = ""
    TextBox.Size = UDim2.new(0, 578, 0, 181)
    TextBox.LayoutOrder = 0
    TextBox.Rotation = 0
    TextBox.Font = Enum.Font.Unknown
    TextBox.BackgroundTransparency = 9
    TextBox.Position = UDim2.new(0, 0, 0.1450626254081726, 0)
    TextBox.FontSize = Enum.FontSize.Size96
    TextBox.ClearTextOnFocus = true
    TextBox.Name = "TextBox"
    TextBox.MaxVisibleGraphemes = -1
    local TextButton = Instance.new("TextButton")
    TextButton.Parent = Frame
    TextButton.LayoutOrder = 0
    TextButton.FontSize = Enum.FontSize.Size14
    TextButton.LineHeight = 1
    TextButton.Active = true
    TextButton.Interactable = true
    TextButton.TextStrokeTransparency = 1
    TextButton.TextTruncate = Enum.TextTruncate.None
    TextButton.SizeConstraint = Enum.SizeConstraint.RelativeXY
    TextButton.ZIndex = 1
    TextButton.BorderSizePixel = 1
    TextButton.Draggable = false
    TextButton.RichText = false
    TextButton.Modal = false
    TextButton.AutoButtonColor = true
    TextButton.SelectionOrder = 0
    TextButton.TextYAlignment = Enum.TextYAlignment.Center
    TextButton.TextScaled = true
    TextButton.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
    TextButton.FontFace = Font.new("rbxasset://fonts/families/Nunito.json", Enum.FontWeight.SemiBold, Enum.FontStyle.Normal)
    TextButton.BorderMode = Enum.BorderMode.Inset
    TextButton.Selectable = true
    TextButton.OpenTypeFeatures = ""
    TextButton.AnchorPoint = Vector2.new(0, 0)
    TextButton.Visible = true
    TextButton.TextXAlignment = Enum.TextXAlignment.Center
    TextButton.BorderColor = BrickColor.new("Black")
    TextButton.TextWrapped = true
    TextButton.Selected = false
    TextButton.AutomaticSize = Enum.AutomaticSize.None
    TextButton.Size = UDim2.new(0, 132, 0, 63)
    TextButton.TextWrap = true
    TextButton.TextTransparency = 0
    TextButton.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
    TextButton.ClipsDescendants = false
    TextButton.BorderColor3 = Color3.fromRGB(27, 42, 53)
    TextButton.Text = "Execute"
    TextButton.TextSize = 14
    TextButton.TextDirection = Enum.TextDirection.Auto
    TextButton.Rotation = 0
    TextButton.Font = Enum.Font.Unknown
    TextButton.BackgroundTransparency = 9
    TextButton.Position = UDim2.new(0.7539269328117371, 0, 0.7799261212348938, 0)
    TextButton.TextColor3 = Color3.fromRGB(255, 255, 255)
    TextButton.MaxVisibleGraphemes = -1
    TextButton.Style = Enum.ButtonStyle.Custom
    TextButton.Name = "TextButton"
    local TextLabel = Instance.new("TextLabel")
    TextLabel.Parent = Frame
    TextLabel.LayoutOrder = 0
    TextLabel.FontSize = Enum.FontSize.Size24
    TextLabel.TextDirection = Enum.TextDirection.Auto
    TextLabel.Active = false
    TextLabel.Interactable = true
    TextLabel.TextStrokeTransparency = 1
    TextLabel.TextTruncate = Enum.TextTruncate.None
    TextLabel.SizeConstraint = Enum.SizeConstraint.RelativeXY
    TextLabel.ZIndex = 1
    TextLabel.BorderSizePixel = 0
    TextLabel.Draggable = false
    TextLabel.RichText = false
    TextLabel.SelectionOrder = 0
    TextLabel.TextYAlignment = Enum.TextYAlignment.Center
    TextLabel.TextScaled = false
    TextLabel.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
    TextLabel.FontFace = Font.new("rbxasset://fonts/families/Michroma.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
    TextLabel.BorderMode = Enum.BorderMode.Outline
    TextLabel.Selectable = false
    TextLabel.OpenTypeFeatures = ""
    TextLabel.AnchorPoint = Vector2.new(0, 0)
    TextLabel.BorderColor = BrickColor.new("Really black")
    TextLabel.Visible = true
    TextLabel.TextXAlignment = Enum.TextXAlignment.Center
    TextLabel.AutomaticSize = Enum.AutomaticSize.None
    TextLabel.Size = UDim2.new(0, 80, 0, 42)
    TextLabel.TextWrapped = false
    TextLabel.TextWrap = false
    TextLabel.TextTransparency = 0
    TextLabel.ClipsDescendants = false
    TextLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
    TextLabel.Text = "KRNL"
    TextLabel.TextStrokeColor3 = Color3.fromRGB(34, 34, 34)
    TextLabel.LineHeight = 1
    TextLabel.Rotation = 0
    TextLabel.Font = Enum.Font.Unknown
    TextLabel.BackgroundTransparency = 0
    TextLabel.Position = UDim2.new(0.4269033372402191, 0, 0, 0)
    TextLabel.TextSize = 24
    TextLabel.MaxVisibleGraphemes = -1
    TextLabel.TextColor3 = Color3.fromRGB(120, 120, 120)
    TextLabel.Name = "TextLabel"
    local UICorner = Instance.new("UICorner")
    UICorner.Parent = Frame
    UICorner.Name = "UICorner"
    UICorner.CornerRadius = UDim.new(0, -2147483648)
  local TextButton_6889 = Instance.new("TextButton")
  TextButton_6889.Parent = huehue
  TextButton_6889.LayoutOrder = 0
  TextButton_6889.FontSize = Enum.FontSize.Size60
  TextButton_6889.LineHeight = 1
  TextButton_6889.Active = true
  TextButton_6889.Interactable = true
  TextButton_6889.TextStrokeTransparency = 1
  TextButton_6889.TextTruncate = Enum.TextTruncate.None
  TextButton_6889.SizeConstraint = Enum.SizeConstraint.RelativeXY
  TextButton_6889.ZIndex = 1
  TextButton_6889.BorderSizePixel = 0
  TextButton_6889.Draggable = false
  TextButton_6889.RichText = false
  TextButton_6889.Modal = false
  TextButton_6889.AutoButtonColor = true
  TextButton_6889.SelectionOrder = 0
  TextButton_6889.TextYAlignment = Enum.TextYAlignment.Center
  TextButton_6889.TextScaled = false
  TextButton_6889.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
  TextButton_6889.FontFace = Font.new("rbxasset://fonts/families/Jura.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
  TextButton_6889.BorderMode = Enum.BorderMode.Outline
  TextButton_6889.Selectable = true
  TextButton_6889.OpenTypeFeatures = ""
  TextButton_6889.AnchorPoint = Vector2.new(0.5, 0.5)
  TextButton_6889.Visible = false
  TextButton_6889.TextXAlignment = Enum.TextXAlignment.Center
  TextButton_6889.BorderColor = BrickColor.new("Magenta")
  TextButton_6889.TextWrapped = true
  TextButton_6889.Selected = false
  TextButton_6889.AutomaticSize = Enum.AutomaticSize.None
  TextButton_6889.Size = UDim2.new(0, 43, 0, 43)
  TextButton_6889.TextWrap = true
  TextButton_6889.TextTransparency = 0
  TextButton_6889.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
  TextButton_6889.ClipsDescendants = false
  TextButton_6889.BorderColor3 = Color3.fromRGB(170, 0, 255)
  TextButton_6889.Text = "KRNL"
  TextButton_6889.TextSize = 50
  TextButton_6889.TextDirection = Enum.TextDirection.Auto
  TextButton_6889.Rotation = 0
  TextButton_6889.Font = Enum.Font.Jura
  TextButton_6889.BackgroundTransparency = 0
  TextButton_6889.Position = UDim2.new(1.5258060693740845, -555, 1.5134934186935425, -280)
  TextButton_6889.TextColor3 = Color3.fromRGB(255, 255, 255)
  TextButton_6889.MaxVisibleGraphemes = -1
  TextButton_6889.Style = Enum.ButtonStyle.Custom
  TextButton_6889.Name = "Open/Close"
    local UICorner = Instance.new("UICorner")
    UICorner.Parent = TextButton_6889
    UICorner.Name = "UICorner"
    UICorner.CornerRadius = UDim.new(0, 756894)
  local Frame_7202 = Instance.new("Frame")
  Frame_7202.Parent = huehue
  Frame_7202.LayoutOrder = 0
  Frame_7202.BorderMode = Enum.BorderMode.Outline
  Frame_7202.Interactable = true
  Frame_7202.AnchorPoint = Vector2.new(0.5, 0.5)
  Frame_7202.BorderColor = BrickColor.new("Really black")
  Frame_7202.SizeConstraint = Enum.SizeConstraint.RelativeXY
  Frame_7202.ZIndex = 1
  Frame_7202.AutomaticSize = Enum.AutomaticSize.None
  Frame_7202.Size = UDim2.new(0, 190, 0, 41)
  Frame_7202.Draggable = false
  Frame_7202.Visible = false
  Frame_7202.ClipsDescendants = false
  Frame_7202.BorderColor3 = Color3.fromRGB(0, 0, 0)
  Frame_7202.Selectable = false
  Frame_7202.Style = Enum.FrameStyle.Custom
  Frame_7202.SelectionOrder = 0
  Frame_7202.Rotation = 0
  Frame_7202.Transparency = 0
  Frame_7202.BackgroundTransparency = 0
  Frame_7202.Position = UDim2.new(0.47291722893714905, 0, 0.9433354735374451, 0)
  Frame_7202.Active = false
  Frame_7202.Name = "Frame AppleGUI"
  Frame_7202.BorderSizePixel = 0
  Frame_7202.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
    local UICorner = Instance.new("UICorner")
    UICorner.Parent = Frame_7202
    UICorner.Name = "UICorner"
    UICorner.CornerRadius = UDim.new(0, 99999)
    local TextActivated = Instance.new("TextLabel")
    TextActivated.Parent = Frame_7202
    TextActivated.LayoutOrder = 0
    TextActivated.FontSize = Enum.FontSize.Size14
    TextActivated.TextDirection = Enum.TextDirection.Auto
    TextActivated.Active = false
    TextActivated.Interactable = true
    TextActivated.TextStrokeTransparency = 1
    TextActivated.TextTruncate = Enum.TextTruncate.None
    TextActivated.SizeConstraint = Enum.SizeConstraint.RelativeXY
    TextActivated.ZIndex = 1
    TextActivated.BorderSizePixel = 0
    TextActivated.Draggable = false
    TextActivated.RichText = false
    TextActivated.SelectionOrder = 0
    TextActivated.TextYAlignment = Enum.TextYAlignment.Center
    TextActivated.TextScaled = false
    TextActivated.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
    TextActivated.FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
    TextActivated.BorderMode = Enum.BorderMode.Outline
    TextActivated.Selectable = false
    TextActivated.OpenTypeFeatures = ""
    TextActivated.AnchorPoint = Vector2.new(0, 0)
    TextActivated.BorderColor = BrickColor.new("Really black")
    TextActivated.Visible = true
    TextActivated.TextXAlignment = Enum.TextXAlignment.Center
    TextActivated.AutomaticSize = Enum.AutomaticSize.XY
    TextActivated.Size = UDim2.new(0, 38, 0, -19)
    TextActivated.TextWrapped = false
    TextActivated.TextWrap = false
    TextActivated.TextTransparency = 0
    TextActivated.ClipsDescendants = false
    TextActivated.BorderColor3 = Color3.fromRGB(0, 0, 0)
    TextActivated.Text = "KRNL Has been activated!"
    TextActivated.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
    TextActivated.LineHeight = 1
    TextActivated.Rotation = 0
    TextActivated.Font = Enum.Font.RobotoMono
    TextActivated.BackgroundTransparency = 0
    TextActivated.Position = UDim2.new(0.05307745561003685, 0, 0.28052279353141785, 0)
    TextActivated.TextSize = 14
    TextActivated.MaxVisibleGraphemes = -1
    TextActivated.TextColor3 = Color3.fromRGB(170, 170, 170)
    TextActivated.Name = "TextActivated"
  local Open = Instance.new("ImageButton")
  Open.Parent = huehue
  Open.LayoutOrder = 0
  Open.Active = true
  Open.Interactable = true
  Open.SizeConstraint = Enum.SizeConstraint.RelativeXY
  Open.ZIndex = 1
  Open.BorderSizePixel = 0
  Open.SliceCenter = Rect.new(0, 0, 0, 0)
  Open.Draggable = false
  Open.ScaleType = Enum.ScaleType.Stretch
  Open.Modal = false
  Open.AutoButtonColor = true
  Open.Transparency = 0
  Open.SelectionOrder = 0
  Open.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
  Open.ImageTransparency = 0
  Open.Selectable = true
  Open.AnchorPoint = Vector2.new(0.5, 0.5)
  Open.Image = "http://www.roblox.com/asset/?id=9288455303"
  Open.TileSize = UDim2.new(1, 0, 1, 0)
  Open.ImageRectSize = Vector2.new(0, 0)
  Open.ImageContent = Content.fromUri("http://www.roblox.com/asset/?id=9288455303")
  Open.Selected = false
  Open.AutomaticSize = Enum.AutomaticSize.None
  Open.Size = UDim2.new(0, 45, 0, 45)
  Open.Visible = false
  Open.HoverImage = ""
  Open.Style = Enum.ButtonStyle.Custom
  Open.ClipsDescendants = false
  Open.BorderColor3 = Color3.fromRGB(0, 0, 0)
  Open.BorderMode = Enum.BorderMode.Outline
  Open.ImageColor3 = Color3.fromRGB(255, 255, 255)
  Open.PressedImage = ""
  Open.Rotation = 0
  Open.ImageRectOffset = Vector2.new(0, 0)
  Open.BackgroundTransparency = 0
  Open.Position = UDim2.new(0.4999999403953552, 0, 0.49867385625839233, 0)
  Open.SliceScale = 1
  Open.ResampleMode = Enum.ResamplerMode.Default
  Open.BorderColor = BrickColor.new("Really black")
  Open.Name = "Open"
    local UICorner = Instance.new("UICorner")
    UICorner.Parent = Open
    UICorner.Name = "UICorner"
    UICorner.CornerRadius = UDim.new(0, 111)
return huehue
